# Generated by Django 6.0.6 on 2026-07-03 20:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses_enabled', models.BooleanField(db_index=True, default=True, verbose_name='Responses enabled?')),
            ],
            options={
                'verbose_name': 'Website Config',
                'db_table': 'reimagining_config',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending review', 'Pending Review'), ('approved', 'Approved'), ('denied archive', 'Denied (but archived)')], db_index=True, default='pending review')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Response',
                'db_table': 'reimagining_response',
            },
        ),
        migrations.CreateModel(
            name='GeopoliticsResponse',
            fields=[
                ('response_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reimagining_app.response')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='In the year')),
                ('question_1', models.TextField(blank=True, null=True, verbose_name='What key geopolitical transformation will the university need to respond to?')),
                ('question_2', models.TextField(blank=True, null=True, verbose_name='Who will the university respond?')),
            ],
            options={
                'verbose_name': 'Geopolitics',
                'db_table': 'reimagining_response_geopolitics',
            },
            bases=('reimagining_app.response',),
        ),
        migrations.CreateModel(
            name='KnowledgeResponse',
            fields=[
                ('response_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reimagining_app.response')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='In the year')),
                ('question_1', models.TextField(blank=True, null=True, verbose_name='What counts as knowledge in this future?')),
                ('question_2', models.TextField(blank=True, null=True, verbose_name='What has the university become?')),
            ],
            options={
                'verbose_name': 'Knowledge',
                'db_table': 'reimagining_response_knowledge',
            },
            bases=('reimagining_app.response',),
        ),
        migrations.CreateModel(
            name='MarketizationResponse',
            fields=[
                ('response_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reimagining_app.response')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='In the year')),
                ('question_1', models.TextField(blank=True, null=True, verbose_name='how do you see this crisis, continuing, evolving, reemerging?')),
                ('question_2', models.TextField(blank=True, null=True, verbose_name='how would you like the university to respond?')),
            ],
            options={
                'verbose_name': 'Marketization',
                'db_table': 'reimagining_response_marketization',
            },
            bases=('reimagining_app.response',),
        ),
        migrations.CreateModel(
            name='MassificationResponse',
            fields=[
                ('response_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reimagining_app.response')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='In the year')),
                ('question_1', models.TextField(blank=True, null=True, verbose_name='What population will the university serve?')),
                ('question_2', models.TextField(blank=True, null=True, verbose_name='How will the university change to accommodate this population?')),
            ],
            options={
                'verbose_name': 'Massification',
                'db_table': 'reimagining_response_massification',
            },
            bases=('reimagining_app.response',),
        ),
        migrations.CreateModel(
            name='RestitutionResponse',
            fields=[
                ('response_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reimagining_app.response')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='In the year')),
                ('question_1', models.TextField(blank=True, null=True, verbose_name='What injustice will the university be forced to address?')),
                ('question_2', models.TextField(blank=True, null=True, verbose_name='How will this restitution transform the university?')),
            ],
            options={
                'verbose_name': 'Restitution',
                'db_table': 'reimagining_response_restitution',
            },
            bases=('reimagining_app.response',),
        ),
        migrations.CreateModel(
            name='TechnologyResponse',
            fields=[
                ('response_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reimagining_app.response')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='In the year')),
                ('question_1', models.TextField(blank=True, null=True, verbose_name='What new technological crisis will the university face?')),
                ('question_2', models.TextField(blank=True, null=True, verbose_name='How will the university face this transformation?')),
            ],
            options={
                'verbose_name': 'Technology',
                'db_table': 'reimagining_response_technology',
            },
            bases=('reimagining_app.response',),
        ),
    ]
